Updated workflow

diff --git a/.github/workflows/apptainer-image.yml b/.github/workflows/apptainer-image.yml
--- a/.github/workflows/apptainer-image.yml
+++ b/.github/workflows/apptainer-image.yml
@@ -81,24 +81,26 @@ jobs:
       run: |
         set -eux
         [ -n "${BASH_VERSION:-}" ] && set -o pipefail
-        export APPTAINER_CACHE_DIR=".setup-downloads/apptainer-cache"
+        export APPTAINER_CACHE_DIR="$(realpath .setup-downloads/apptainer-cache)"
+        mkdir -p .setup-downloads
+        mkdir -p sif
         pushd  "${DEF_DIR}"
         echo "Building \"${IMAGE_NAME}.sif\""
         touch .build-arg-file
-        apptainer build --warn-unused-build-args --fix-perms --force --build-arg-file .build-arg-file ../../sifs/"${IMAGE_NAME}.sif" Singularity || { echo "Failed to build \"${IMAGE_NAME}.sif\""; exit 1; }
+        apptainer build --warn-unused-build-args --fix-perms --force --build-arg-file .build-arg-file ../../sif/"${IMAGE_NAME}.sif" Singularity || { echo "Failed to build \"${IMAGE_NAME}.sif\""; exit 1; }
         echo "Built \"${IMAGE_NAME}.sif\""
         popd
     - name: Login and Deploy Container
       run: |
         set -eux
         [ -n "${BASH_VERSION:-}" ] && set -o pipefail
-        [ -r "sifs/${IMAGE_NAME}.sif" ] || { echo "No container named sifs/${IMAGE_NAME:-}.sif found."; exit 1; }
+        [ -r "sif/${IMAGE_NAME}.sif" ] || { echo "No container named sif/${IMAGE_NAME:-}.sif found."; exit 1; }
         echo "Container size:"
-        du -h "sifs/${IMAGE_NAME}.sif"
+        du -h "sif/${IMAGE_NAME}.sif"
         echo "Disk usage:"
         df -h
-        echo "Pushing sifs/${IMAGE_NAME}.sif to ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG}"
+        echo "Pushing \"sif/${IMAGE_NAME}.sif\" to ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG}"
         apptainer remote login -u ${{ github.actor }} -p ${{ secrets.TOKEN }} oras://ghcr.io
-        apptainer push -U "sifs/${IMAGE_NAME}.sif" oras://ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG} || { echo "Failed to push sifs/${IMAGE_NAME}.sif to ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG}"; exit 1; }
-        echo "Pushed sifs/${IMAGE_NAME}.sif to ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG}"
+        apptainer push -U "sif/${IMAGE_NAME}.sif" oras://ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG} || { echo "Failed to push \"sif/${IMAGE_NAME}.sif\' to ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG}"; exit 1; }
+        echo "Pushed \"sif/${IMAGE_NAME}.sif\" to ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG}"
         
