Fix

diff --git a/def/hyakvnc-freesurfer-ubuntu22.04/Singularity b/def/hyakvnc-freesurfer-ubuntu22.04/Singularity
--- a/def/hyakvnc-freesurfer-ubuntu22.04/Singularity
+++ b/def/hyakvnc-freesurfer-ubuntu22.04/Singularity
@@ -1,48 +1,45 @@
-Bootstrap: {{BOOTSTRAP_SOURCE}}
-From: {{BOOTSTRAP_FROM_REPO}}/{{BOOTSTRAP_FROM_IMAGE}}{{BOOTSTRAP_FROM_SUFFIX}}
+Bootstrap: docker
+From: ubuntu:22.04
 
 %arguments
-	BOOTSTRAP_SOURCE=localimage
-	BOOTSTRAP_FROM_REPO=../../sif
-	BOOTSTRAP_FROM_IMAGE=hyakvnc-vncserver-ubuntu22.04
-	BOOTSTRAP_FROM_SUFFIX=.sif
 	FREESURFER_VERSION=7.4.1
-	FREESURFER_DOWNLOAD_URL=https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/{{FREESURFER_VERSION}}/freesurfer_ubuntu22-{{FREESURFER_VERSION}}_amd64.deb
-	FREESURFER_DOWNLOAD_FILENAME=freesurfer_ubuntu22-{{FREESURFER_VERSION}}_amd64.deb
-	SETUP_DOWNLOADS_DIR=../../.setup-downloads
 	RECON_ALL_CLINICAL_HASH=ecdf46e
 	RECON_ALL_CLINICAL_URL=https://raw.githubusercontent.com/freesurfer/freesurfer/{{RECON_ALL_CLINICAL_HASH}}/recon_all_clinical/recon-all-clinical.sh
   MCR_VERSION=R2014b
+  # SETUP_DOWNLOADS_MOUNT [optional] [default: "/opt/.setup-downloads"] The path to the directory where the setup files will be downloaded. This directory should be mounted as a volume in the container.
+  SETUP_DOWNLOADS_MOUNT=/opt/.setup-downloads
 
 %help
 This is an Apptainer container of Ubuntu 22.04 with FreeSurfer installed. It is designed to be run on the Hyak cluster at the University of Washington with the hyakvnc script.
 
 %setup
-	[ -n "${APPTAINER_ROOTFS:-}" ] && ../../bin/write-apptainer-labels.sh > "${APPTAINER_ROOTFS}/.build_labels"
-	mkdir -p "{{SETUP_DOWNLOADS_DIR}}"
-	if ! [ -r "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" ]; then
-		command -v curl >/dev/null 2>&1 || { echo "warning: curl not found!" >&2; exit 1; }
-		curl --fail --fail-early --compressed --location \
-			--output "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" \
-			"{{FREESURFER_DOWNLOAD_URL}}" || { echo "warning: curl failed!" >&2; rm -fv "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" >&2; exit 1; }
-		echo "Downloaded \"{{FREESURFER_DOWNLOAD_FILENAME}}\" from \"{{FREESURFER_DOWNLOAD_URL}}\"."
-	fi
-	ln -v "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" "${APPTAINER_ROOTFS}/freesurfer.deb" || { echo "warning: ln failed!" >&2; exit 1; }
+	../../bin/write-apptainer-labels.sh > "${APPTAINER_ROOTFS}/.build_labels"
+  [ -n "${SETUP_DOWNLOADS_MOUNT:-{{SETUP_DOWNLOADS_MOUNT}}}" ] && export SETUP_DOWNLOADS_MOUNT="${SETUP_DOWNLOADS_MOUNT:-{{SETUP_DOWNLOADS_MOUNT}}}" && mkdir -p "${APPTAINER_ROOTFS}/${SETUP_DOWNLOADS_MOUNT}"
+
+%labels
+	edu.uw.hyakvnc.container.resources.recommends.mem 16G
+	edu.uw.hyakvnc.container.resources.requires.mem 8G
+	edu.uw.hyakvnc.container.resources.recommends.cpus 4
+	edu.uw.hyakvnc.container.resources.requires.cpus 1
+	edu.uw.hyakvnc.container.resources.suggests.gpus 1
 	
 %files
+  ../../common /opt/setup
 	../../common/configs/freesurfer/start-freeview.sh /usr/local/bin/start-freeview
 	../../common/configs/freesurfer/freeview.desktop /usr/share/applications/freeview.desktop
 
 %post
-	set -eux
-	export DEBIAN_FRONTEND=noninteractive
+	set -x
+  export DEBIAN_FRONTEND=noninteractive
+  export DOWNLOAD_DIR="${DOWNLOAD_DIR:-${SETUP_DOWNLOADS_MOUNT:-/opt/.setup-downloads}}" && mkdir -p "${DOWNLOAD_DIR}" && ls -la "${DOWNLOAD_DIR}"
 
-	# Update the package list:
-	apt-get update -y -qq
+  apt-get update -y -qq
 
-	# Install FreeSurfer:
-	dpkg --install --force-depends /freesurfer.deb && apt-get install --fix-broken --yes --quiet
-	unlink /freesurfer.deb
+  # Install Ubuntu packages:
+  /opt/setup/scripts/install-hyakvnc-ubuntu22.04.sh || { echo "ERROR: install-hyakvnc-ubuntu22.04.sh failed!" >&2; exit 1; }
+
+  # Install FreeSurfer:
+  /opt/setup/scripts/install-freesurfer.sh || { echo "ERROR: install-freesurfer.sh failed!" >&2; exit 1; }
 
 	# Link /usr/local/freesurfer/dev to /usr/local/freesurfer/{{FREESURFER_VERSION}}:
 	# (fixes some scripts that expect this)
@@ -54,43 +51,55 @@ This is an Apptainer container of Ubuntu 22.04 with FreeSurfer installed. It is 
 		"{{RECON_ALL_CLINICAL_URL}}" || { echo "warning: curl failed!" >&2; exit 1; }
 	chmod a+x /usr/local/freesurfer/{{FREESURFER_VERSION}}/bin/recon-all-clinical.sh
 
+
+  export FREESURFER_HOME="/usr/local/freesurfer/{{FREESURFER_VERSION}}"
+
+  [ -d "${FREESURFER_HOME}" ] || { echo "ERROR: FREESURFER_HOME directory not found!" >&2; exit 1; }
+
+  # Set up the environment by sourcing the FreeSurfer setup script, filtering out the environment variables that are already set in the container, and writing the remaining environment variables to the /.singularity.d/env directory:
+    printenv | grep -oE '.*='  | tr -d '=' | sort | uniq  > /tmp/current_env_names.txt
+    bash -c "source "${FREESURFER_HOME}/SetUpFreeSurfer.sh" && printenv"  > /tmp/freesurfer_env.txt
+    grep -oE '.*='  /tmp/freesurfer_env.txt | tr -d '=' | sort | uniq > /tmp/freesurfer_env_names.txt
+    unique_freesurfer_env_names="$(comm -13 /tmp/current_env_names.txt /tmp/freesurfer_env_names.txt | paste -s -d'|' || true)"
+    
+    echo "export FREESURFER_HOME=\"${FREESURFER_HOME}\"" >> /.singularity.d/env/101-hyakvnc-freesurfer-env.sh
+    grep -E "^($unique_freesurfer_env_names)=" /tmp/freesurfer_env.txt | sed 's/^/export /g'  >> /.singularity.d/env/101-hyakvnc-freesurfer-env.sh
+
+    freesurfer_path="$(grep -oE '^PATH=.*' /tmp/freesurfer_env.txt | sed 's/^PATH=//; s/:/\n/g' | cat -n | sort -uk2 | sort -n | cut -f2- | grep -F "${FREESURFER_HOME}" | paste -s -d':' || true)"
+    [ -n "$freesurfer_path" ] && echo "export PATH=\"${freesurfer_path}:\${PATH}\"" >> /.singularity.d/env/101-hyakvnc-freesurfer-env.sh
+
+  # Show the contents of the environment file:
+    [ -f "/singularity.d/env/101-hyakvnc-freesurfer-env.sh" ] && echo >&2 "/singularity.d/env/101-hyakvnc-freesurfer-env.sh contents:" && cat "/singularity.d/env/101-hyakvnc-freesurfer-env.sh" >&2
+  
 	# Install Matlab Compiler Runtime (MCR) if requested:
   if [ -n "{{MCR_VERSION}}" ]; then
     # Install MCR dependencies:
     apt-get install -y libxt-dev libxext-dev libncurses5
     
 		# Set the environment variables for fs_install_mcr to work:
-		export FREESURFER_HOME="/usr/local/freesurfer/{{FREESURFER_VERSION}}"
 		export PATH="${FREESURFER_HOME}/bin:${PATH}"
 
     # Install MCR:
     fs_install_mcr "{{MCR_VERSION}}"
   fi
+
+	# Erase the setup files:
+	rm -rf /opt/setup
+
 	# Clean up packages:
 	apt-get clean -y -qq && apt-get -y autoremove && rm -rf /var/lib/apt/lists/*
 
 %environment
-	export FREESURFER_HOME="/usr/local/freesurfer/{{FREESURFER_VERSION}}"
-	# Settings from SetupFreeSurfer.sh:
-	export OS="Linux"
-	export FS_OVERRIDE=0
-	export FIX_VERTEX_AREA=""
-	export FSF_OUTPUT_FORMAT="nii.gz"
-	export SUBJECTS_DIR="${FREESURFER_HOME}/subjects"
-	export FUNCTIONALS_DIR="${FREESURFER_HOME}/sessions"
-	export MNI_DIR="${FREESURFER_HOME}/mni"
-	export LOCAL_DIR="${FREESURFER_HOME}/local"
-	export MINC_BIN_DIR="${FREESURFER_HOME}/mni/bin"
-	export MINC_LIB_DIR="${FREESURFER_HOME}/mni/lib" 
-	export MNI_DATAPATH="${FREESURFER_HOME}/mni/data"
-	export PERL5LIB="${MINC_LIB_DIR}/perl5/5.8.5"
-	export MNI_PERL5LIB="${MINC_LIB_DIR}/perl5/5.8.5"
-	export PATH="${FREESURFER_HOME}/bin:${FREESURFER_HOME}/tktools:${MINC_BIN_DIR}:${PATH}"
-	export FS_LICENSE="${FS_LICENSE:-${HOME}/${USER}/.freesurfer_license.txt}"
+	export SHELL="${SHELL:-/bin/bash}"
 
-%labels
-	edu.uw.hyakvnc.container.resources.recommends.mem 16G
-	edu.uw.hyakvnc.container.resources.requires.mem 8G
-	edu.uw.hyakvnc.container.resources.recommends.cpus 4
-	edu.uw.hyakvnc.container.resources.requires.cpus 1
-	edu.uw.hyakvnc.container.resources.suggests.gpus 1
+%runscript
+  hyakvnc-vncserver "$@"
+
+%startscript
+  hyakvnc-vncserver "$@"
+
+%apprun vncserver
+  hyakvnc-vncserver "$@"
+
+%appstart vncserver
+  hyakvnc-vncserver "$@"
diff --git a/def/hyakvnc-vncserver-ubuntu22.04/Singularity b/def/hyakvnc-vncserver-ubuntu22.04/Singularity
--- a/def/hyakvnc-vncserver-ubuntu22.04/Singularity
+++ b/def/hyakvnc-vncserver-ubuntu22.04/Singularity
@@ -5,154 +5,35 @@ From: ubuntu:22.04
 This is an Apptainer container of Ubuntu 22.04 with TurboVNC and XFCE installed. It is intended to be used as a base for other containers that need a VNC server. It is designed to be run on the Hyak cluster at the University of Washington with the hyakvnc script.
 
 %arguments
-	TURBOVNC_VERSION=3.1
-	TURBOVNC_DOWNLOAD_URL=https://sourceforge.net/projects/turbovnc/files/{{TURBOVNC_VERSION}}/turbovnc_{{TURBOVNC_VERSION}}_amd64.deb
-	TURBOVNC_DOWNLOAD_FILENAME=turbovnc_{{TURBOVNC_VERSION}}_amd64.deb
-	SETUP_DOWNLOADS_DIR=../../.setup-downloads
+# SETUP_DOWNLOADS_MOUNT [optional] [default: "/opt/.setup-downloads"] The path to the directory where the setup files will be downloaded. This directory should be mounted as a volume in the container.
+  SETUP_DOWNLOADS_MOUNT="/opt/.setup-downloads"
 
 %setup
-	[ -n "${APPTAINER_ROOTFS:-}" ] && ../../bin/write-apptainer-labels.sh > "${APPTAINER_ROOTFS}/.build_labels"
-	mkdir -p "{{SETUP_DOWNLOADS_DIR}}"
-	if ! [ -r "{{SETUP_DOWNLOADS_DIR}}/{{TURBOVNC_DOWNLOAD_FILENAME}}" ]; then
-		command -v curl >/dev/null 2>&1 || { echo "warning: curl not found!" >&2; exit 1; }
-		curl --fail --fail-early --compressed --location \
-			--continue-at - \
-			--output "{{SETUP_DOWNLOADS_DIR}}/{{TURBOVNC_DOWNLOAD_FILENAME}}" \
-			"{{TURBOVNC_DOWNLOAD_URL}}" || { echo "warning: curl failed!" >&2; rm -fv "{{SETUP_DOWNLOADS_DIR}}/TURBOVNC_DOWNLOAD_FILENAME}}" >&2; exit 1; }
-		echo "Downloaded \"{{TURBOVNC_DOWNLOAD_FILENAME}}\" from \"{{TURBOVNC_DOWNLOAD_URL}}\"."
-	fi
-	ln -v "{{SETUP_DOWNLOADS_DIR}}/{{TURBOVNC_DOWNLOAD_FILENAME}}" "${APPTAINER_ROOTFS}/turbovnc.deb" || { echo "warning: ln failed!" >&2; exit 1; }
+	../../bin/write-apptainer-labels.sh > "${APPTAINER_ROOTFS}/.build_labels"
+  [ -n "${SETUP_DOWNLOADS_MOUNT:-}" ] && export SETUP_DOWNLOADS_MOUNT="${SETUP_DOWNLOADS_MOUNT}" && mkdir -p "${APPTAINER_ROOTFS}/${SETUP_DOWNLOADS_MOUNT}"
 
 %labels
-	edu.uw.hyakvnc.container.resources.recommends.mem 4G
-	edu.uw.hyakvnc.container.resources.requires.mem 4G
-	edu.uw.hyakvnc.container.resources.recommends.cpus 2
+	edu.uw.hyakvnc.container.resources.recommends.mem 2G
+	edu.uw.hyakvnc.container.resources.requires.mem 2G
+	edu.uw.hyakvnc.container.resources.recommends.cpus 1
 	edu.uw.hyakvnc.container.resources.requires.cpus 1
 	
 %files
-	../../common/configs/ubuntu /opt/setup/configs
-	./hyakvnc-vncserver.sh /opt/local/bin/hyakvnc-vncserver
+  ../../common /opt/setup
 
 %post
-{
-	set -eux
-	export DEBIAN_FRONTEND=noninteractive
+	set -x
+  export DEBIAN_FRONTEND=noninteractive
+  apt-get update -y -qq
 
-	apt-get update -y -qq
-	apt-get install -y -qq \
-		apt-utils \
-		apt-transport-https \
-		localepurge
-
-	# Don't generate these locales"
-	mkdir -p /var/lib/locales/supported.d
-	for localename in fr de zh-hant ja es it zh-hans pt ru ar; do
-		touch "/var/lib/locales/supported.d/${localename}" && chmod a-r "/var/lib/locales/supported.d/${localename}"
-	done
-
-	# Limit the English locales to en_US.UTF-8:
-	echo "en_US.UTF-8 UTF-8" > /var/lib/locales/supported.d/en && chmod a-r /var/lib/locales/supported.d/en
-
-	# Generate the locales
-	apt-get install -y locales
-	localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.utf8
-
-	# Set the locale environment variables permanently:
-	export LANG=en_US.utf8 && echo "LANG=\"${LANG}\"" >>/etc/environment
-	export LC_ALL=en_US.utf8 && echo "LC_ALL=\"${LC_ALL}\"" >>/etc/environment
-	export LC_COLLATE=C && echo "LC_COLLATE=\"${LC_COLLATE}\"" >>/etc/environment
-
-	# Stop apt from installing audio packages (they don't work on VNC):
-	apt-mark hold xfce4-pulseaudio-plugin pavucontrol pulseaudio pipewire pipewire-bin pipewire-pulse
-
-	# Install basic packages:
-	apt-get install -yq --no-install-recommends \
-		bash-completion \
-		bc \
-		binutils \
-		bzip2 \
-		curl \
-		dash \
-		ed \
-		file \
-		git \
-		less \
-		make \
-		nano \
-		netcat-openbsd \
-		openssh-client \
-		patch \
-		procps \
-		psmisc \
-		python3 \
-		rsync \
-		unzip \
-		vim-tiny \
-		zip
-
-	# Install XFCE and some apps:
-	apt-get install -yq --no-install-recommends \
-		at-spi2-core \
-		dbus-x11 \
-		elementary-xfce-icon-theme \
-		fonts-dejavu-core \
-		fonts-freefont-ttf \
-		fonts-ubuntu \
-		gettext \
-		greybird-gtk-theme \
-		libfile-mimeinfo-perl \
-		libnet-dbus-perl \
-		libnotify-bin \
-		libx11-protocol-perl \
-		libxfce4ui-utils \
-		mousepad \
-		novnc \
-		ristretto \
-		thunar \
-		thunar-archive-plugin \
-		thunar-volman \
-		x11-utils \
-		x11-xserver-utils \
-		xauth \
-		xclip \
-		xdg-user-dirs \
-		xdg-utils \
-		xfce4-appfinder \
-		xfce4-datetime-plugin \
-		xfce4-indicator-plugin \
-		xfce4-notes-plugin \
-		xfce4-notifyd \
-		xfce4-panel \
-		xfce4-screenshooter \
-		xfce4-session \
-		xfce4-settings \
-		xfce4-taskmanager \
-		xfce4-terminal \
-		xfce4-whiskermenu-plugin \
-		xfconf \
-		xfdesktop4 \
-		xfonts-base \
-		xfwm4 \
-		xterm
-	
-	# Set xfce4-terminal as default terminal emulator:
-	update-alternatives --set x-terminal-emulator /usr/bin/xfce4-terminal.wrapper
-
-	# Install TurboVNC:
-	dpkg --install --force-depends /turbovnc.deb && apt-get install --fix-broken --yes --quiet
-	unlink /turbovnc.deb
-
-	# shellcheck disable=SC2016
-	echo '$vncUserDir = "$ENV{VNC_USER_DIR}";' >>/etc/turbovncserver.conf
-	# Copy configs:
-	rsync -avi --no-p --no-g --chmod=ugo=rwX /opt/setup/configs/ /
+  # Install Ubuntu packages:
+  /opt/setup/install-hyakvnc-ubuntu22.04.sh || { echo "ERROR: install-hyakvnc-ubuntu22.04.sh failed!" >&2; exit 1; }
 
 	# Erase the setup files:
 	rm -rf /opt/setup
 
 	# Clean up packages:
-	apt-get clean -y -qq && rm -rf /var/lib/apt/lists/*
-}
+	apt-get clean -y -qq && apt-get -y autoremove && rm -rf /var/lib/apt/lists/*
 
 %environment
 	export LANG=en_US.utf8
@@ -162,11 +43,7 @@ This is an Apptainer container of Ubuntu 22.04 with TurboVNC and XFCE installed.
 	export PATH="/opt/local/bin:/opt/TurboVNC/bin:${PATH}"
 
 %runscript
-{
-	exec hyakvnc-vncserver "$@"
-}
+  hyakvnc-vncserver "$@"
 
 %startscript
-{
-	exec hyakvnc-vncserver "$@"
-}
+  hyakvnc-vncserver "$@"
